# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e87d46b293d9f808df1e1856473143dd7d9497cc6b184bd2f33fdf18ad7586abe4c6f3fc4af319298ccdcd50c5ce0ffd1eaa8d8bdc7a44434d4464b95f74929e

test:
  secret_key_base: 64a359af475a7e8b8caad098c2ef107ad0f0f1d1760cf3463573e6f942309f6847a4e140994091943e944e44a0ff3dbb175816e7a8bf81221f73a1d04be34c36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
